### ISSUE TITLE
GDM fails to start with 340.102

### ISSUE THREAD

**Issue by RedDwarf69** [negativo17/nvidia-driver-340#1]
When updating to akmod-nvidia 2:340.102-1.fc25 my system started freezing just before starting GDM. I have a computer again just because rpmfusion still has 340.101.

Fully updated system with kernel-4.9.10-200.fc25.x86_64.

**Comment by scaronni** [comment]
I'm not maintaining 340 drivers officially as I've really no interest in them and no hardware to test; so that's why there is no advertisement. I have a few users requesting them, but I'm not able to provide any support apart from building them.

Do you have any message or log? Otherwise I think it's time for me to trash the repository.

Regards,
--Simone

**Comment by RedDwarf69** [comment]
Not sure which logs I should include. But to be honest, this is my employer office computer: I shouldn't be spending a lot of time debugging this and if I keep having problems with the card (nouveau continuously  froze the computer while using it) I will just request to my manager a different one.

So... don't keep the repository just because of me, I understand if you want to get rid of it.

**Comment by scaronni** [comment]
New build coming with an updated patch.
I will make a note on the blog and remove it in a few weeks.
